'use client'
import React from "react"

import { useState } from 'react'
import { X } from 'react-feather'

type Item = {
  // Autogenerated ID
  id: string
  name: string
  complete: boolean
}

// TODO: Allow re-ordering the list 🤔
export default function ShoppingList() {
  const [items, setItems] = useState<Record<string, Item>>({})

  function addNewItem(name: string) {
    const id = crypto.randomUUID()
    setItems((items) => ({
      ...items,
      [id]: { id: id, name: name, complete: false },
    }))
  }

  function completeItemById(id: string) {
    const item = items[id]
    item.complete = true

    setItems((items) => ({
      ...items,
      [id]: item,
    }))
  }

  const itemList = Object.entries(items)
    .filter(([_, item]) => !item.complete)
    .map(([id, item]) => (
      <li
        className="p-2 border-b border-rose-500 border-dotted last:border-0 flex justify-between"
        key={id}
      >
        <span>{item.name}</span>
        <span
          onClick={() => {
            completeItemById(id)
          }}
        >
          <X />
        </span>
      </li>
    ))
  return (
    <div className="text-black bg-rose-200 p-4">
      <ol className="p-4 bg-white mb-4 overflow-scroll rounded-lg drop-shadow-lg">
        {itemList.length ? (
          itemList
        ) : (
          <span className="text-gray-500">
            Nothing to do. Add some items to the list ☀️
          </span>
        )}
      </ol>
      <AddNewItemForm
        handleAddItem={(name: string) => {
          addNewItem(name)
        }}
      />
    </div>
  )
}

function AddNewItemForm(props: { handleAddItem: (item: string) => void }) {
  const [item, setItem] = useState('')

  return (
    <div className="bg-white p-1 rounded-xl">
      <form
        onSubmit={(e) => {
          e.preventDefault()
          props.handleAddItem(item)
          setItem('')
        }}
        className="p-4 border border-dashed border-rose-900 rounded-xl flex"
      >
        <input
          type="text"
          value={item}
          onChange={(e) => {
            setItem(e.target.value)
          }}
          className="border border-gray-400 px-4 py-2 rounded-l-lg flex-1"
        />
        <button className="bg-rose-500 px-4 py-2 border border-rose-500 rounded-r-lg">
          Add
        </button>
      </form>
    </div>
  )
}
